import React from "react";
export const initialData = [
  {
    product: "Scissors",
    quantity: 1,
    equipmentId: "12e",
    rfidTagId: "12t",
    dateAdded: "11/12/22",
    location: "OT",
  },
  {
    product: "Knife",
    quantity: 2,
    equipmentId: "13e",
    rfidTagId: "21t",
    dateAdded: "21/12/22",
    location: "OT",
  },
  {
    product: "Forceps",
    quantity: 3,
    equipmentId: "14e",
    rfidTagId: "13t",
    dateAdded: "5/12/22",
    location: "OT",
  },
  {
    product: "Retractors",
    quantity: 2,
    equipmentId: "15e",
    rfidTagId: "14t",
    dateAdded: "8/12/22",
    location: "SR",
  },
  {
    product: "Needle Holders",
    quantity: 5,
    equipmentId: "16e",
    rfidTagId: "15t",
    dateAdded: "9/1/23",
    location: "OT",
  },
  {
    product: "Hemostats",
    quantity: 2,
    equipmentId: "17e",
    rfidTagId: "16t",
    dateAdded: "9/1/23",
    location: "OT",
  },
  {
    product: "Towel Clamps",
    quantity: 3,
    equipmentId: "18e",
    rfidTagId: "17t",
    dateAdded: "15/12/23",
    location: "SR",
  },
  {
    product: "Towel Clamps",
    quantity: 5,
    equipmentId: "19e",
    rfidTagId: "18t",
    dateAdded: "6/6/23",
    location: "OT",
  },
  {
    product: "Coca cola",
    quantity: 2,
    equipmentId: "20e",
    rfidTagId: "19t",
    dateAdded: "11/11/22",
    location: "Tr",
  },
  {
    product: "Surgical Gloves",
    quantity: 10,
    equipmentId: "21e",
    rfidTagId: "20t",
    dateAdded: "12/11/22",
    location: "OT",
  },
  {
    product: "Surgical Mask",
    quantity: 50,
    equipmentId: "22e",
    rfidTagId: "21t",
    dateAdded: "13/11/22",
    location: "OT",
  },
  {
    product: "Surgical Gown",
    quantity: 15,
    equipmentId: "23e",
    rfidTagId: "22t",
    dateAdded: "14/11/22",
    location: "OT",
  },
  {
    product: "Syringe",
    quantity: 100,
    equipmentId: "24e",
    rfidTagId: "23t",
    dateAdded: "15/11/22",
    location: "OT",
  },
  {
    product: "Stethoscope",
    quantity: 5,
    equipmentId: "25e",
    rfidTagId: "24t",
    dateAdded: "16/11/22",
    location: "OT",
  },
  {
    product: "Thermometer",
    quantity: 4,
    equipmentId: "26e",
    rfidTagId: "25t",
    dateAdded: "17/11/22",
    location: "OT",
  },
];
